# Generated by Django 4.2.30 on 2026-04-27 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('execution_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Время выполнения')),
                ('memory_used_kb', models.IntegerField(blank=True, null=True, verbose_name='Память (КБ)')),
                ('solved_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата решения')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.submissionstatus', verbose_name='Статус')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='task.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_solutions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Решение задачи',
                'verbose_name_plural': 'Решения задач',
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
