# Generated by Django 4.2.30 on 2026-05-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
