# Generated by Django 4.2.30 on 2026-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_solutionvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='passed_tests',
            field=models.IntegerField(default=0, verbose_name='Пройдено тестов'),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_tests',
            field=models.IntegerField(default=0, verbose_name='Всего тестов'),
        ),
    ]
