# Generated by Django 6.0.5 on 2026-05-22 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Награда за участие (XP)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_course',
            field=models.BooleanField(default=False, verbose_name='Это учебный курс'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стек технологий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='projectvacancy',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание требований'),
        ),
        migrations.AlterField(
            model_name='projectvacancy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectvacancy',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.role', verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(default='Ожидает', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кандидат')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectvacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'unique_together': {('vacancy', 'user')},
            },
        ),
    ]
